# 2023-09-17 09:00
name: act Build Windows

# on: [push, pull_request, workflow_dispatch]
on: [workflow_dispatch]

env:
  TAG_NAME: DXVK
  VERSION: v2.3

jobs:
  build-set-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup glslangValidator
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/HansKristian-Work/vkd3d-proton-ci/main/glslangValidator.exe" -OutFile "glslangValidator.exe"
        Write-Output "$pwd" | Out-File -FilePath "${Env:GITHUB_PATH}" -Append

    - name: Setup Meson
      shell: pwsh
      run: pip install meson

    - name: Find Visual Studio
      shell: pwsh
      run: |
        $installationPath = Get-VSSetupInstance `
          | Select-VSSetupInstance -Require Microsoft.VisualStudio.Workload.NativeDesktop -Latest `
          | Select-Object -ExpandProperty InstallationPath
        Write-Output "VSDEVCMD=${installationPath}\Common7\Tools\VsDevCmd.bat" `
          | Out-File -FilePath "${Env:GITHUB_ENV}" -Append

    - name: Build MSVC x86
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x86 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        meson --buildtype release --backend vs2022 build-msvc-x86
        msbuild -m build-msvc-x86/dxvk.sln

    - name: Create Zip Archive Release - x86
      uses: deep-soft/zip-release@v2
      with:
        type: 'zip'
        filename: '${{ env.TAG_NAME }}-${{ env.VERSION }}-x86.zip'
        directory: 'build-msvc-x86'
        inclusions: '*.dll'
        exclusions: '*.map *.pdb'
        recursive_exclusions: '*.map *.pdb'
        path: '.'
        env_variable: 'ZIP_RELEASE_ARCHIVE_x86'
      # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

    - name: Build MSVC x64
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x64 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        meson --buildtype release --backend vs2022 build-msvc-x64
        msbuild -m build-msvc-x64/dxvk.sln

    - name: Create Zip Archive Release - x64
      uses: deep-soft/zip-release@v2
      with:
        type: 'zip'
        filename: '${{ env.TAG_NAME }}-${{ env.VERSION }}-x64.zip'
        directory: 'build-msvc-x64'
        inclusions: '*.dll'
        exclusions: '*.map *.pdb'
        recursive_exclusions: '*.map *.pdb'
        path: '.'
        env_variable: 'ZIP_RELEASE_ARCHIVE_x64'
      # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

# zip release begin
    - name: Create Zip Archive Release - ALL
      uses: deep-soft/zip-release@v2
      with:
        type: 'zip'
        filename: '${{ env.TAG_NAME }}-${{ env.VERSION }}-all.zip'
        directory: '.'
        exclusions: '*.map *.pdb'
        recursive_exclusions: '*.map *.pdb'
        path: '.'
        env_variable: 'ZIP_RELEASE_ARCHIVE_ALL'
      # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

    - name: Upload zip
      continue-on-error: true
      uses: deep-soft/upload-artifact@main
      with:
        name: '${{ env.TAG_NAME }}-${{ env.VERSION }}-all'
        path: '${{ env.ZIP_RELEASE_ARCHIVE_ALL }}'

    - name: Publish
      continue-on-error: true
      uses: deep-soft/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}-${{ env.VERSION }}
        files: |
          ${{ env.ZIP_RELEASE_ARCHIVE_x64 }}
          ${{ env.ZIP_RELEASE_ARCHIVE_x86 }}
          ${{ env.ZIP_RELEASE_ARCHIVE_ALL }}
# zip release end
